// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf_knx0Q-32ULWDOYgCOTiRaUYn1F4wxI',
    appId: '1:278147187924:web:1e3651383fb5ed868fe741',
    messagingSenderId: '278147187924',
    projectId: 'messagedatabase-bcd44',
    authDomain: 'messagedatabase-bcd44.firebaseapp.com',
    storageBucket: 'messagedatabase-bcd44.firebasestorage.app',
    measurementId: 'G-73G4CR62WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVLmVYUq82u3ir8p5OSgnG601feNrE0_4',
    appId: '1:278147187924:android:f536c737033561f18fe741',
    messagingSenderId: '278147187924',
    projectId: 'messagedatabase-bcd44',
    storageBucket: 'messagedatabase-bcd44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbpboaAc6cNorMPiEONG7hxVTBnp5a_LY',
    appId: '1:278147187924:ios:8ed543d9a47b21ac8fe741',
    messagingSenderId: '278147187924',
    projectId: 'messagedatabase-bcd44',
    storageBucket: 'messagedatabase-bcd44.firebasestorage.app',
    iosBundleId: 'com.example.appMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbpboaAc6cNorMPiEONG7hxVTBnp5a_LY',
    appId: '1:278147187924:ios:8ed543d9a47b21ac8fe741',
    messagingSenderId: '278147187924',
    projectId: 'messagedatabase-bcd44',
    storageBucket: 'messagedatabase-bcd44.firebasestorage.app',
    iosBundleId: 'com.example.appMessage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf_knx0Q-32ULWDOYgCOTiRaUYn1F4wxI',
    appId: '1:278147187924:web:6f4f46ec8ffeda7b8fe741',
    messagingSenderId: '278147187924',
    projectId: 'messagedatabase-bcd44',
    authDomain: 'messagedatabase-bcd44.firebaseapp.com',
    storageBucket: 'messagedatabase-bcd44.firebasestorage.app',
    measurementId: 'G-ED3GZSVX1S',
  );
}
